{% set name = "casadi" %}
{% set version = "3.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/casadi/casadi/archive/{{ version }}.tar.gz
  sha256: 7107e9dad9c6ffd6433e68f646a7b8da9e37daf7e7dd69e828b3f486cd428443

build:
  number: 0
  skip: true  # [win and py]
  skip: true  # [py<36]
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('casadi', max_pin='x.x') }}

requirements:
  build:
    - pkg-config
    - cmake
    - ninja
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - python
    - swig
    - numpy
    - ipopt

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ipopt

test:
  imports:
    - casadi  # [not win]
  files:
    - ipopt_nl.py  # [not win]
  commands: python ipopt_nl.py  # [not win]

about:
  home: http://casadi.org
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: CasADi is a symbolic framework for numeric optimization

extra:
  recipe-maintainers:
    - pstjohn
    - pariterre
